server: 
  port: 8080
  context-path: /xwj
  tomcat:
    uri-encoding: UTF-8
  jsp-servlet:
    init-parameters:
      development: true
  
spring: 
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://dev.yonyouccs.com:3001/custom-zjtl
    username: devmysql
    password: DG3kCZ2Jcmpm
  profiles.active: prd
    
name: com.xwj